Repository openshift/windows-machine-config-bootstrapper, pull requests merged in 2019-12, with the labels that each got.

#106 [wsu] Switch to AMD instance type for e2e tests
  tools/ansible/tasks/wsu/test/e2e/wsu_test.go
Labels: approved, lgtm, size/XS

#107 [ci] Setup hybrid networking in WSU e2e tests
  hack/run-wsu-ci-e2e-test.sh
Labels: approved, lgtm, size/XS

#104 [wsu] Run the OVN hybrid overlay
  hack/run-wsu-ci-e2e-test.sh
  tools/ansible/tasks/wsu/main.yaml
  tools/ansible/tasks/wsu/test/e2e/wsu_test.go
Labels: approved, lgtm, size/M

#96 [wmcb] Add support for CNI configuration
  cmd/bootstrapper/configure_cni.go
  cmd/bootstrapper/initialize_kubelet.go
  docs/README.md
  pkg/bootstrapper/bootstrapper.go
  pkg/bootstrapper/bootstrapper_test.go
  test/e2e/bootstrapper_test.go
  test/e2e/configure_cni_test.go
Labels: approved, lgtm, size/XL

#108 Update .gitignore with wni generated files
  .gitignore
Labels: approved, lgtm, size/XS

#105 Bug 1768835: Fix pod manifest directory creation
  pkg/bootstrapper/bootstrapper.go
  pkg/bootstrapper/bootstrapper_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#103 Refactor tests
  hack/run-wmcb-ci-e2e-test.sh
  hack/run-wsu-ci-e2e-test.sh
  internal/test/framework/framework.go
  internal/test/go.mod
  internal/test/go.sum
  internal/test/wmcb/main_test.go
  internal/test/wmcb/wmcb_test.go
  internal/test/wmcb_test.go
  internal/test/wsu/main_test.go
  internal/test/wsu/wsu_test.go
  tools/ansible/tasks/wsu/test/e2e/go.mod
  tools/ansible/tasks/wsu/test/e2e/go.sum
Labels: approved, lgtm, size/XXL

#102 [wmcb] Fix path separators for Windows paths
  pkg/bootstrapper/bootstrapper.go
  pkg/bootstrapper/bootstrapper_test.go
  test/e2e/bootstrapper_test.go
  test/e2e/configure_cni_test.go
Labels: approved, lgtm, size/M

#111 [wni][azure] Fix rule handling
  tools/windows-node-installer/README.md
  tools/windows-node-installer/pkg/cloudprovider/azure/vm.go
  tools/windows-node-installer/test/e2e/azure_test.go
Labels: approved, lgtm, size/L

#110 [wsu] Configure CNI on bootstrapped nodes
  internal/test/framework/framework.go
  internal/test/go.sum
  internal/test/wsu/wsu_test.go
  tools/ansible/tasks/wsu/main.yaml
Labels: approved, lgtm, size/L

#113 [ci] wsu test refactor follow-up
  internal/test/framework/framework.go
  internal/test/wsu/wsu_test.go
Labels: approved, lgtm, size/M

#114 [wsu] Dynamically generate the CNI config
  internal/test/framework/framework.go
  internal/test/go.mod
  internal/test/go.sum
  internal/test/wsu/wsu_test.go
  tools/ansible/tasks/wsu/main.yaml
  tools/ansible/tasks/wsu/templates/cni.j2
Labels: approved, lgtm, size/L

#112 [docs] Update README to reflect recent changes
  docs/README.md
Labels: approved, lgtm, size/XS

#115 [ci] Improve WMCB unit test failure checking
  internal/test/wmcb/wmcb_test.go
Labels: approved, lgtm, size/XS

#118 [wsu] Run kube-proxy as a Windows service
  internal/test/wsu/wsu_test.go
  tools/ansible/tasks/wsu/main.yaml
  tools/ansible/tasks/wsu/powershell/hns.psm1
Labels: approved, lgtm, size/L
