Repository openshift/windows-machine-config-bootstrapper, pull requests merged in 2019-11, with the labels that each got.

#72 [wmcb] Reflect "initialize_kubelet" cmd in...
  cmd/bootstrapper/initialize_kubelet.go
  docs/README.md
Labels: approved, lgtm, size/S

#66 [wmcb] Update Makefile with GO_BUILD_ARGS
  Makefile
Labels: approved, lgtm, size/XS

#73 Bug 1768568: [logging] Allow redirects for Ruby installer download
  tools/ansible/README.md
  tools/ansible/tasks/logging/install_fluentd.yml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#76 [wmcb] Fix e2e tests that reference "run"
  Makefile
  docs/README.md
  test/e2e/bootstrapper_test.go
Labels: approved, lgtm, size/S

#75 Dockerfile for CI
  Dockerfile.tools
Labels: approved, lgtm, size/S

#78 Add git to build_root dockerfile
  Dockerfile.tools
Labels: approved, lgtm, size/XS

#79 Add make to build_root dockerfile
  Dockerfile.tools
Labels: approved, lgtm, size/XS

#81 Specify root user in Dockerfile.tools
  Dockerfile.tools
Labels: approved, lgtm, size/XS

#83 Specify gocache location in Dockerfile.tools
  Dockerfile.tools
Labels: approved, lgtm, size/XS

#64 [docs] [wni] [aws] Update wni create command with updated flags
  tools/windows-node-installer/README.md
Labels: approved, lgtm, size/XS

#84 Use go1.12.13 in Dockerfile.tools
  Dockerfile.tools
Labels: approved, lgtm, size/XS

#74 [wmcb] framework to run unit tests
  hack/run-wmcb-ci-e2e-test.sh
  internal/internal.go
  internal/test/go.mod
  internal/test/go.sum
  internal/test/wmcb_test.go
Labels: approved, lgtm, size/XL

#80 [logging] E2E tests for logging playbook
  tools/ansible/tasks/logging/test/logging_test.go
Labels: approved, lgtm, size/M

#82 Fix go mod issues
  Makefile
  go.mod
  go.sum
  tools/windows-node-installer/cmd/root.go
  tools/windows-node-installer/go.mod
  tools/windows-node-installer/go.sum
  tools/windows-node-installer/log/log.go
Labels: approved, lgtm, size/L

#88 Change Dockerfile.tools for new CI template
  Dockerfile.tools
  hack/run-wsu-ci-e2e-test.sh
Labels: approved, lgtm, size/S

#86 [wmcb] Register kubelet with Windows taint
  docs/README.md
  hack/run-wmcb-ci-e2e-test.sh
  internal/test/go.mod
  internal/test/wmcb_test.go
  pkg/bootstrapper/bootstrapper.go
Labels: approved, lgtm, size/M

#87 Bug 1761745: [wmcb] Add worker label to the Windows Node
  pkg/bootstrapper/bootstrapper.go
  pkg/bootstrapper/bootstrapper_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#77 [wni][azure] Enable and configure the winrm port for windows node
  Makefile
  tools/windows-node-installer/README.md
  tools/windows-node-installer/go.sum
  tools/windows-node-installer/pkg/cloudprovider/azure/vm.go
  tools/windows-node-installer/test/e2e/azure_test.go
Labels: approved, lgtm, size/L

#89 [wsu] enable e2e tests
  Dockerfile.tools
  hack/run-wsu-ci-e2e-test.sh
  tools/ansible/tasks/wsu/test/e2e/wsu_test.go
Labels: approved, lgtm, size/M

#65 [wmcb] Add more context to bootstrap error msgs
  pkg/bootstrapper/bootstrapper.go
Labels: approved, lgtm, size/XS

#92 [wmcb] [ci] Remove unnecessary vars
  internal/test/wmcb_test.go
Labels: approved, lgtm, size/XS

#94 [wmcb] Change node labels during kubelet registration
  internal/test/wmcb_test.go
  pkg/bootstrapper/bootstrapper.go
  pkg/bootstrapper/bootstrapper_test.go
Labels: approved, lgtm, size/M

#97 [wmcb] Cleanup assert usage
  pkg/bootstrapper/bootstrapper_test.go
  test/e2e/bootstrapper_test.go
Labels: approved, lgtm, size/S

#91 [docs] Remove ref to keypairs
  tools/windows-node-installer/README.md
Labels: approved, lgtm, size/XS

#98 Bug 1775384: [wsu] Upgrade kubelet version to 1.16
  tools/ansible/tasks/wsu/main.yaml
  tools/ansible/tasks/wsu/test/e2e/wsu_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#93 [wsu] Run WMCB through WSU
  hack/run-wsu-ci-e2e-test.sh
  tools/ansible/README.md
  tools/ansible/tasks/wsu/main.yaml
  tools/ansible/tasks/wsu/test/e2e/go.mod
  tools/ansible/tasks/wsu/test/e2e/wsu_test.go
Labels: approved, lgtm, size/L

#99 [wni] Cleanup assert usage
  tools/windows-node-installer/pkg/resource/tracker_test.go
  tools/windows-node-installer/test/e2e/aws_test.go
  tools/windows-node-installer/test/e2e/azure_test.go
Labels: approved, lgtm, size/M

#100 [wmcb] minor assert fix
  test/e2e/bootstrapper_test.go
Labels: approved, lgtm, size/XS

#95 [wsu] apply worker roles
  tools/ansible/tasks/wsu/main.yaml
  tools/ansible/tasks/wsu/test/e2e/wsu_test.go
Labels: approved, lgtm, size/M
