Repository openshift/windows-machine-config-bootstrapper, pull requests merged in 2019-10, with the labels that each got.

#29 [docs][wni] README update
  tools/windows-node-installer/README.md
Labels: approved, lgtm, size/M

#34 [wni] cmd help output change
  tools/windows-node-installer/cmd/aws.go
  tools/windows-node-installer/cmd/root.go
Labels: approved, lgtm, size/S

#37 [WNI] Combine unnecessary AWS structs
  tools/windows-node-installer/cmd/aws.go
Labels: approved, lgtm

#38 [wni] Refactor interface to be cloud provider agnostic
  tools/windows-node-installer/cmd/aws.go
  tools/windows-node-installer/pkg/cloudprovider/aws/ec2.go
  tools/windows-node-installer/pkg/cloudprovider/factory.go
Labels: approved, lgtm, size/M

#40 Bug 1757446: [wni] Directory validation errors
  tools/windows-node-installer/pkg/cloudprovider/factory.go
  tools/windows-node-installer/pkg/cloudprovider/factory_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#41 [wni] add tools e2e test
  Makefile
  go.sum
  tools/windows-node-installer/go.sum
  tools/windows-node-installer/test/e2e/aws_test.go
Labels: approved, lgtm, size/L

#43 [wni] Fix the trailing slash
  tools/windows-node-installer/pkg/cloudprovider/factory.go
  tools/windows-node-installer/pkg/cloudprovider/factory_test.go
Labels: approved, lgtm, size/XS

#44 [wni] Fix the path validation err
  tools/windows-node-installer/pkg/cloudprovider/factory.go
  tools/windows-node-installer/pkg/cloudprovider/factory_test.go
Labels: approved, lgtm, size/M

#32 [aws] Enable winrm when launching Windows instance
  tools/windows-node-installer/pkg/cloudprovider/aws/ec2.go
Labels: approved, lgtm, size/M

#45 [wni] Fix test panics
  tools/windows-node-installer/test/e2e/aws_test.go
Labels: approved, lgtm, size/XS

#48 [wni] Add tags for Windows instance created
  tools/windows-node-installer/pkg/cloudprovider/aws/ec2.go
  tools/windows-node-installer/test/e2e/aws_test.go
Labels: approved, lgtm, size/L

#47 [aws] Ensure winrm port is open
  tools/windows-node-installer/pkg/cloudprovider/aws/ec2.go
Labels: approved, lgtm, size/M

#46 [wsu] WSU playbook
  docs/README.md
  tools/ansible/README.md
  tools/ansible/tasks/wsu/main.yaml
Labels: approved, lgtm, size/L

#24 [wni] Azure Implementation
  go.mod
  go.sum
  tools/windows-node-installer/README.md
  tools/windows-node-installer/cmd/aws.go
  tools/windows-node-installer/cmd/azure.go
  tools/windows-node-installer/go.sum
  tools/windows-node-installer/pkg/cloudprovider/azure/vm.go
  tools/windows-node-installer/pkg/cloudprovider/factory.go
  tools/windows-node-installer/pkg/resource/tracker.go
Labels: approved, lgtm, size/XXL

#53 Bug 1760536: [wsu] Fixing kubelet path
  tools/ansible/tasks/wsu/main.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#49 [wni] add tools e2e test
  tools/windows-node-installer/pkg/cloudprovider/aws/ec2.go
  tools/windows-node-installer/test/e2e/aws_test.go
Labels: approved, lgtm, size/L

#42 [logging] Install Fluentd on Windows instance
  tools/ansible/tasks/logging/README.md
  tools/ansible/tasks/logging/install_fluentd.yml
  tools/ansible/tasks/logging/main.yml
Labels: approved, lgtm, size/M

#57 [wmcb] Add Makefile target for unit test binary
  Makefile
  docs/README.md
Labels: approved, lgtm, size/S

#60 Add vendor directory to .gitignore
  .gitignore
Labels: approved, lgtm, size/XS

#59 [wni] Fix broken go.sum
  go.mod
  go.sum
  tools/windows-node-installer/go.mod
  tools/windows-node-installer/go.sum
Labels: approved, lgtm, size/L

#61 [ci] Add placeholder script and target
  Makefile
  hack/run-wmcb-ci-e2e-test.sh
Labels: approved, lgtm, size/S

#62 [wni] fix wni aws output
  tools/windows-node-installer/cmd/aws.go
Labels: approved, lgtm, size/XS

#54 [wmcb] e2e test to check if kubelet is running
  test/e2e/bootstrapper_test.go
Labels: approved, lgtm, size/M

#52 [aws-wni] Provide credentials to access Windows Node
  tools/windows-node-installer/cmd/aws.go
  tools/windows-node-installer/cmd/azure.go
  tools/windows-node-installer/pkg/cloudprovider/aws/ec2.go
  tools/windows-node-installer/pkg/cloudprovider/aws/ec2_test.go
  tools/windows-node-installer/pkg/cloudprovider/azure/vm.go
  tools/windows-node-installer/pkg/cloudprovider/factory.go
  tools/windows-node-installer/pkg/types/types.go
  tools/windows-node-installer/test/e2e/aws_test.go
Labels: approved, lgtm, size/L

#39 Fluentd plugins ansible playbook
  tools/ansible/tasks/logging/install_plugins.yml
  tools/ansible/tasks/logging/main.yml
  tools/ansible/tasks/logging/test/logging_test.go
Labels: approved, lgtm, size/M

#55 [docs] Update to Contribution guideline
  CONTRIBUTION.md
Labels: approved, lgtm, size/XS

#63 [wsu][ci] Add placeholder script and target
  Makefile
  hack/run-wsu-ci-e2e-test.sh
Labels: approved, lgtm, size/S

#70 [wmcb] Rename "run" command to "configure-kubelet"
  cmd/bootstrapper/configure_kubelet.go
  docs/README.md
  pkg/bootstrapper/bootstrapper.go
Labels: approved, lgtm, size/M

#68 [wsu] Initial e2e framework and test
  hack/run-wsu-ci-e2e-test.sh
  tools/ansible/tasks/wsu/test/e2e/go.mod
  tools/ansible/tasks/wsu/test/e2e/go.sum
  tools/ansible/tasks/wsu/test/e2e/wsu_test.go
Labels: approved, lgtm, size/L

#69 [wni] [aws] Open SSH port for Windows instance created
  tools/windows-node-installer/go.sum
  tools/windows-node-installer/pkg/cloudprovider/aws/ec2.go
  tools/windows-node-installer/test/e2e/aws_test.go
Labels: approved, lgtm, size/M
