Repository openshift/windows-machine-config-bootstrapper, pull requests merged in 2019-09, with the labels that each got.

#7 [git] modify gitignore to exclude IDE settings
  .gitignore
Labels: lgtm, size/XS

#8 [docs] Update contribution guidelines
  CONTRIBUTION.md
  images/PR-workflow.png
Labels: lgtm, size/S

#6 [wni] initialize windows-node-installer structure
  tools/windows-node-installer/Makefile
  tools/windows-node-installer/README.md
  tools/windows-node-installer/go.mod
  tools/windows-node-installer/go.sum
  tools/windows-node-installer/pkg/client/openshift.go
  tools/windows-node-installer/pkg/cloudprovider/factory.go
  tools/windows-node-installer/pkg/cloudprovider/interface.go
Labels: approved, size/L

#9 [wni] Fix inital framework
  tools/windows-node-installer/go.mod
  tools/windows-node-installer/go.sum
  tools/windows-node-installer/main.go
Labels: approved, lgtm, size/L

#13 [wni] Merging factory and interface
  tools/windows-node-installer/pkg/cloudprovider/factory.go
  tools/windows-node-installer/pkg/cloudprovider/interface.go
Labels: approved, lgtm, size/M

#18 Remove blank line from Makefile
  Makefile
Labels: approved, lgtm, size/XS

#12 [wni] AWS implementation
  Makefile
  go.mod
  go.sum
  tools/windows-node-installer/README.md
  tools/windows-node-installer/cmd/create.go
  tools/windows-node-installer/cmd/destroy.go
  tools/windows-node-installer/cmd/log.go
  tools/windows-node-installer/cmd/main.go
  tools/windows-node-installer/go.mod
  tools/windows-node-installer/go.sum
  tools/windows-node-installer/main.go
  tools/windows-node-installer/pkg/client/openshift.go
  tools/windows-node-installer/pkg/cloudprovider/aws/ec2.go
  tools/windows-node-installer/pkg/cloudprovider/factory.go
  tools/windows-node-installer/pkg/resource/data/sample-windows-node-installer.json
  tools/windows-node-installer/pkg/resource/tracker.go
  tools/windows-node-installer/pkg/resource/tracker_test.go
Labels: approved, lgtm, size/XXL

#11 [docs] Update CONTRIBUTION guideline
  CONTRIBUTION.md
Labels: approved, lgtm, size/XS

#30 Add gofmt
  Makefile
  hack/verify-gofmt.sh
Labels: approved, lgtm, size/M

#20 [wmcb] Intial bootstrapper implementation
  Makefile
  cmd/bootstrapper/main.go
  cmd/bootstrapper/run.go
  cmd/bootstrapper/start.go
  docs/README.md
  go.mod
  go.sum
  pkg/bootstrapper/bootstrapper.go
  pkg/bootstrapper/bootstrapper_test.go
  pkg/bootstrapper/node_bootstrapper.go
  test/e2e/bootstrapper_test.go
  test/e2e/main_test.go
Labels: approved, lgtm, size/XXL

#33 Update WMCB README
  docs/README.md
Labels: approved, lgtm, size/XS
