Repository openshift/windows-machine-config-bootstrapper, pull requests merged in 2020-07, with the labels that each got.

#218 [wsu] [ci] Add user-agent for ignition url
  internal/test/wmcb/powershell/wget-ignore-cert.ps1
  internal/test/wmcb/wmcb_test.go
  tools/ansible/tasks/wsu/main.yaml
Labels: approved, lgtm

#216 Bug 1814433: [wmcb] Generate Windows specific kubelet config
  Makefile
  go.mod
  go.sum
  hack/generate-conf-files.sh
  hack/verify-gofmt.sh
  pkg/bootstrapper/bindata.go
  pkg/bootstrapper/bootstrapper.go
  pkg/bootstrapper/bootstrapper_test.go
  pkg/bootstrapper/templates/kubelet_config.json
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#221 Bug 1859537: Add retries for SSH config
  internal/test/framework/framework.go
  tools/ansible/tasks/wsu/main.yaml
  tools/windows-node-installer/pkg/cloudprovider/aws/ec2.go
  tools/windows-node-installer/pkg/cloudprovider/azure/vm.go
  tools/windows-node-installer/pkg/types/types.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#220 [wmcb] Change kubelet log directory
  internal/test/framework/framework.go
  internal/test/wsu/wsu_test.go
  pkg/bootstrapper/bootstrapper.go
  pkg/bootstrapper/bootstrapper_test.go
  test/e2e/bootstrapper_test.go
  tools/ansible/tasks/wsu/main.yaml
Labels: approved, lgtm
