Repository openshift/windows-machine-config-bootstrapper, pull requests merged in 2020-01, with the labels that each got.

#121 Bug 1787646: Update hybrid-overlay.exe for 4.4
  internal/test/wsu/wsu_test.go
  tools/ansible/tasks/wsu/main.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#120 [ci] Update framework for launching multiple VMs
  internal/test/framework/framework.go
  internal/test/framework/windowsvm.go
  internal/test/wmcb/main_test.go
  internal/test/wmcb/wmcb_test.go
  internal/test/wsu/main_test.go
  internal/test/wsu/wsu_test.go
Labels: approved, lgtm, size/XL

#122 [ci] Add options for working with existing VMs
  hack/run-wmcb-ci-e2e-test.sh
  hack/run-wsu-ci-e2e-test.sh
  internal/test/framework/framework.go
  internal/test/framework/windowsvm.go
  internal/test/wmcb/main_test.go
  internal/test/wsu/main_test.go
  tools/ansible/README.md
Labels: approved, lgtm, size/L

#124 Bug 1776506: Allow WSU to be run multiple times
  hack/run-wsu-ci-e2e-test.sh
  internal/test/wsu/wsu_test.go
  tools/ansible/tasks/wsu/main.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#126 [ci] Fix skipVMSetup command line option
  hack/run-wmcb-ci-e2e-test.sh
  hack/run-wsu-ci-e2e-test.sh
Labels: approved, lgtm, size/XS

#128 [ci] Update Windows VM ami
  internal/test/framework/framework.go
  tools/windows-node-installer/test/e2e/aws_test.go
Labels: approved, lgtm

#130 [wni][aws][azure] Capture windows user in credentials
  tools/windows-node-installer/pkg/cloudprovider/aws/ec2.go
  tools/windows-node-installer/pkg/cloudprovider/azure/vm.go
  tools/windows-node-installer/pkg/types/types.go
Labels: approved, lgtm, size/S

#129 [wni][aws] Avoid creating another instance in e2e
  tools/windows-node-installer/test/e2e/aws_test.go
Labels: approved, lgtm, size/S

#131 Map OpenShift release version to WMCB version to support OpenShift 4.3
  Dockerfile.tools
  tools/ansible/tasks/wsu/main.yaml
Labels: approved, lgtm, size/M

#125 [wni][azure][aws] Open port 10250 via firewall
  tools/windows-node-installer/go.mod
  tools/windows-node-installer/go.sum
  tools/windows-node-installer/pkg/cloudprovider/aws/ec2.go
  tools/windows-node-installer/pkg/cloudprovider/azure/vm.go
  tools/windows-node-installer/pkg/types/types.go
  tools/windows-node-installer/test/e2e/aws_test.go
  tools/windows-node-installer/test/e2e/azure_test.go
  tools/windows-node-installer/test/e2e/common.go
Labels: approved, lgtm, size/L

#133 [ci] Enable running of bootstrapper tests
  docs/README.md
  hack/run-wmcb-ci-e2e-test.sh
  internal/test/framework/framework.go
  internal/test/wmcb/powershell/wget-ignore-cert.ps1
  internal/test/wmcb/wmcb_test.go
  internal/test/wsu/wsu_test.go
  test/e2e/bootstrapper_test.go
  test/e2e/configure_cni_test.go
Labels: approved, lgtm, size/L

#134 [wni][aws] Fix subnet selection
  tools/windows-node-installer/README.md
  tools/windows-node-installer/pkg/cloudprovider/aws/ec2.go
Labels: approved, lgtm, size/M

#136 [wni] Use latest Windows image
  tools/windows-node-installer/README.md
  tools/windows-node-installer/cmd/aws.go
  tools/windows-node-installer/pkg/cloudprovider/aws/ec2.go
  tools/windows-node-installer/test/e2e/aws_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#135 Bug 1794182: Resolve missing kubelet log level
  internal/test/framework/framework.go
  internal/test/go.mod
  internal/test/go.sum
  pkg/bootstrapper/bootstrapper.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#137 [wmcb] Redirect kubelet log to log directory
  pkg/bootstrapper/bootstrapper.go
  pkg/bootstrapper/bootstrapper_test.go
  test/e2e/bootstrapper_test.go
Labels: approved, lgtm, size/S
