Repository openshift/windows-machine-config-bootstrapper, pull requests merged in 2020-05, with the labels that each got.

#192 [ci] Remove dependency on oc binary
  Dockerfile.tools
  hack/run-wmcb-ci-e2e-test.sh
  hack/run-wsu-ci-e2e-test.sh
  internal/test/framework/framework.go
  internal/test/wmcb/wmcb_test.go
  internal/test/wsu/wsu_test.go
Labels: approved, lgtm

#191 [wni] Fix unit test changes
  tools/windows-node-installer/pkg/cloudprovider/aws/ec2_test.go
Labels: approved, lgtm

#190 [release-4.4] Backport from master 05-01-2020
  Dockerfile.tools
  Makefile
  hack/run-wmcb-ci-e2e-test.sh
  hack/run-wsu-ci-e2e-test.sh
  internal/test/framework/framework.go
  internal/test/wmcb/wmcb_test.go
  internal/test/wsu/wsu_test.go
  tools/ansible/docs/Dev Preview with OCP 4.4 on AWS.pdf
  tools/ansible/docs/Dev Preview with OCP 4.4 on Azure.pdf
  tools/windows-node-installer/pkg/cloudprovider/aws/ec2.go
  tools/windows-node-installer/pkg/cloudprovider/aws/ec2_test.go
Labels: approved, lgtm

#195 [ci] Step registry fixes
  Dockerfile.tools
Labels: approved, lgtm

#176 Bug 1823919: [ci] React to upstream kube-ovn changes
  internal/test/framework/framework.go
  internal/test/wmcb/wmcb_test.go
  internal/test/wsu/wsu_test.go
  tools/ansible/tasks/wsu/main.yaml
  tools/ansible/tasks/wsu/templates/cni.j2
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#193 [wni] Don't panic on AWS session creation error
  tools/windows-node-installer/pkg/cloudprovider/aws/ec2.go
Labels: approved, lgtm

#170 [wmcb] Dynamically pick the kube-node package in the e2e tests
  internal/test/framework/framework.go
  internal/test/wmcb/pkginfo.go
  internal/test/wmcb/wmcb_test.go
Labels: approved, lgtm

#186 [wni] Add programmatic retrieval of backendPoolID
  tools/windows-node-installer/pkg/cloudprovider/azure/vm.go
  tools/windows-node-installer/test/e2e/azure_test.go
Labels: approved, lgtm

#173 Bug 1818026: Redirect WMCB info logs to stdout
  cmd/bootstrapper/configure_cni.go
  cmd/bootstrapper/initialize_kubelet.go
  cmd/bootstrapper/main.go
  tools/ansible/tasks/wsu/main.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#178 [wni]Use pod permissions to create and delete instances
  tools/windows-node-installer/go.mod
  tools/windows-node-installer/pkg/client/openshift.go
  tools/windows-node-installer/pkg/cloudprovider/factory.go
  tools/windows-node-installer/test/e2e/aws_test.go
  tools/windows-node-installer/test/e2e/azure_test.go
  tools/windows-node-installer/test/e2e/clustersetup.go
  tools/windows-node-installer/test/e2e/deploy/cluster_role_binding.yaml
  tools/windows-node-installer/test/e2e/deploy/clusterole.yaml
  tools/windows-node-installer/test/e2e/deploy/namespace.yaml
  tools/windows-node-installer/test/e2e/deploy/role.yaml
  tools/windows-node-installer/test/e2e/deploy/role_binding.yaml
  tools/windows-node-installer/test/e2e/deploy/service_account.yaml
Labels: approved, lgtm

#199 [release-4.4] Backport from master 05-13-2020
  Dockerfile.tools
  cmd/bootstrapper/configure_cni.go
  cmd/bootstrapper/initialize_kubelet.go
  cmd/bootstrapper/main.go
  internal/test/framework/framework.go
  internal/test/wmcb/pkginfo.go
  internal/test/wmcb/wmcb_test.go
  internal/test/wsu/wsu_test.go
  tools/ansible/tasks/wsu/main.yaml
  tools/ansible/tasks/wsu/templates/cni.j2
  tools/windows-node-installer/go.mod
  tools/windows-node-installer/pkg/client/openshift.go
  tools/windows-node-installer/pkg/cloudprovider/aws/ec2.go
  tools/windows-node-installer/pkg/cloudprovider/azure/vm.go
  tools/windows-node-installer/pkg/cloudprovider/factory.go
  tools/windows-node-installer/test/e2e/aws_test.go
  tools/windows-node-installer/test/e2e/azure_test.go
  tools/windows-node-installer/test/e2e/clustersetup.go
  tools/windows-node-installer/test/e2e/deploy/cluster_role_binding.yaml
  tools/windows-node-installer/test/e2e/deploy/clusterole.yaml
  tools/windows-node-installer/test/e2e/deploy/namespace.yaml
  tools/windows-node-installer/test/e2e/deploy/role.yaml
  tools/windows-node-installer/test/e2e/deploy/role_binding.yaml
  tools/windows-node-installer/test/e2e/deploy/service_account.yaml
Labels: approved, lgtm

#200 [wni] Make azure WNI use the given credential file
  Makefile
  tools/windows-node-installer/README.md
  tools/windows-node-installer/cmd/azure.go
  tools/windows-node-installer/go.mod
  tools/windows-node-installer/pkg/cloudprovider/azure/vm.go
  tools/windows-node-installer/pkg/cloudprovider/factory.go
  tools/windows-node-installer/test/e2e/aws_test.go
  tools/windows-node-installer/test/e2e/azure_test.go
  tools/windows-node-installer/test/e2e/common.go
Labels: approved, lgtm

#196 [docs] Convert WinC AWS docs to Markdown
  tools/ansible/docs/aws/aws-with-windows-server.md
  tools/ansible/docs/images/aws-add-tags.png
  tools/ansible/docs/images/aws-apply-role.png
  tools/ansible/docs/images/aws-attach-replace-iam-role.png
  tools/ansible/docs/images/aws-autoassign.png
  tools/ansible/docs/images/aws-change-security-groups.png
  tools/ansible/docs/images/aws-connect-get-password.png
  tools/ansible/docs/images/aws-connect-to-instance.png
  tools/ansible/docs/images/aws-connect.png
  tools/ansible/docs/images/aws-create-instance.png
  tools/ansible/docs/images/aws-edit-inbound-rules.png
  tools/ansible/docs/images/aws-enable-autoassign.png
  tools/ansible/docs/images/aws-instance-type.png
  tools/ansible/docs/images/aws-launch.png
  tools/ansible/docs/images/aws-new-key-pair.png
  tools/ansible/docs/images/aws-next-steps.png
  tools/ansible/docs/images/aws-resources.png
  tools/ansible/docs/images/aws-security-group.png
  tools/ansible/docs/images/aws-tags.png
  tools/ansible/docs/images/aws-vpc.png
  tools/ansible/docs/images/aws-windows-server.png
Labels: approved, lgtm

#197 [docs] Convert WinC Azure docs to Markdown
  tools/ansible/docs/azure/azure-with-windows-server.md
  tools/ansible/docs/images/azure-admin-account.png
  tools/ansible/docs/images/azure-create-instance-complete.png
  tools/ansible/docs/images/azure-create-instance.png
  tools/ansible/docs/images/azure-create-resource.png
  tools/ansible/docs/images/azure-inbound-security-rules.png
  tools/ansible/docs/images/azure-load-balancer.png
  tools/ansible/docs/images/azure-networking.png
  tools/ansible/docs/images/azure-public-ip-info.png
  tools/ansible/docs/images/azure-public-ip.png
  tools/ansible/docs/images/azure-resource-group-region.png
  tools/ansible/docs/images/azure-security-comms.png
  tools/ansible/docs/images/azure-security-groups.png
  tools/ansible/docs/images/azure-security-rdp.png
  tools/ansible/docs/images/azure-security-rules-final.png
  tools/ansible/docs/images/azure-security-winrm.png
  tools/ansible/docs/images/azure-set-load-balancer.png
  tools/ansible/docs/images/azure-tags.png
  tools/ansible/docs/images/azure-vm.png
Labels: approved, lgtm

#198 [docs] Convert general WinC doc to Markdown
  tools/ansible/docs/images/gen-public-ip.png
  tools/ansible/docs/ocp-4-4-with-windows-server.md
Labels: approved, lgtm

#202 [release-4.4] Backport from master 05-20-2020
  Makefile
  tools/ansible/docs/aws/aws-with-windows-server.md
  tools/ansible/docs/azure/azure-with-windows-server.md
  tools/ansible/docs/images/aws-add-tags.png
  tools/ansible/docs/images/aws-apply-role.png
  tools/ansible/docs/images/aws-attach-replace-iam-role.png
  tools/ansible/docs/images/aws-autoassign.png
  tools/ansible/docs/images/aws-change-security-groups.png
  tools/ansible/docs/images/aws-connect-get-password.png
  tools/ansible/docs/images/aws-connect-to-instance.png
  tools/ansible/docs/images/aws-connect.png
  tools/ansible/docs/images/aws-create-instance.png
  tools/ansible/docs/images/aws-edit-inbound-rules.png
  tools/ansible/docs/images/aws-enable-autoassign.png
  tools/ansible/docs/images/aws-instance-type.png
  tools/ansible/docs/images/aws-launch.png
  tools/ansible/docs/images/aws-new-key-pair.png
  tools/ansible/docs/images/aws-next-steps.png
  tools/ansible/docs/images/aws-resources.png
  tools/ansible/docs/images/aws-security-group.png
  tools/ansible/docs/images/aws-tags.png
  tools/ansible/docs/images/aws-vpc.png
  tools/ansible/docs/images/aws-windows-server.png
  tools/ansible/docs/images/azure-admin-account.png
  tools/ansible/docs/images/azure-create-instance-complete.png
  tools/ansible/docs/images/azure-create-instance.png
  tools/ansible/docs/images/azure-create-resource.png
  tools/ansible/docs/images/azure-inbound-security-rules.png
  tools/ansible/docs/images/azure-load-balancer.png
  tools/ansible/docs/images/azure-networking.png
  tools/ansible/docs/images/azure-public-ip-info.png
  tools/ansible/docs/images/azure-public-ip.png
  tools/ansible/docs/images/azure-resource-group-region.png
  tools/ansible/docs/images/azure-security-comms.png
  tools/ansible/docs/images/azure-security-groups.png
  tools/ansible/docs/images/azure-security-rdp.png
  tools/ansible/docs/images/azure-security-rules-final.png
  tools/ansible/docs/images/azure-security-winrm.png
  tools/ansible/docs/images/azure-set-load-balancer.png
  tools/ansible/docs/images/azure-tags.png
  tools/ansible/docs/images/azure-vm.png
  tools/ansible/docs/images/gen-public-ip.png
  tools/ansible/docs/ocp-4-4-with-windows-server.md
  tools/windows-node-installer/README.md
  tools/windows-node-installer/cmd/azure.go
  tools/windows-node-installer/go.mod
  tools/windows-node-installer/pkg/cloudprovider/azure/vm.go
  tools/windows-node-installer/pkg/cloudprovider/factory.go
  tools/windows-node-installer/test/e2e/aws_test.go
  tools/windows-node-installer/test/e2e/azure_test.go
  tools/windows-node-installer/test/e2e/common.go
Labels: approved, lgtm

#201 [wni]Fix Windows VM leaks in CI
  tools/windows-node-installer/pkg/cloudprovider/aws/ec2.go
Labels: approved, lgtm

#203 [wmcb] Bump wni version to reflect latest changes
  internal/test/go.mod
  internal/test/go.sum
Labels: approved, lgtm

#204 Bug 1841140: fix getting kube node binary SHA
  tools/ansible/tasks/wsu/main.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
