Repository openshift/windows-machine-config-bootstrapper, pull requests merged in 2020-02, with the labels that each got.

#139 [ci] Enable running of WMCB CNI e2e tests
  internal/test/framework/framework.go
  internal/test/framework/windowsvm.go
  internal/test/go.mod
  internal/test/go.sum
  internal/test/test.go
  internal/test/wmcb/templates/cni.template
  internal/test/wmcb/wmcb_test.go
  internal/test/wsu/wsu_test.go
Labels: approved, lgtm, size/XL

#140 [ci] Allow multiple VMs to be tested at once
  hack/run-wsu-ci-e2e-test.sh
  internal/test/go.sum
  internal/test/wsu/wsu_test.go
  tools/ansible/tasks/wsu/main.yaml
Labels: approved, lgtm, size/L

#144 Reflect renaming of repository
  CONTRIBUTION.md
  Dockerfile.tools
  Makefile
  cmd/bootstrapper/configure_cni.go
  cmd/bootstrapper/initialize_kubelet.go
  go.mod
  internal/test/framework/framework.go
  internal/test/framework/windowsvm.go
  internal/test/go.mod
  internal/test/go.sum
  internal/test/wmcb/main_test.go
  internal/test/wmcb/wmcb_test.go
  internal/test/wsu/main_test.go
  internal/test/wsu/wsu_test.go
  test/e2e/bootstrapper_test.go
  test/e2e/configure_cni_test.go
  tools/ansible/README.md
  tools/ansible/tasks/logging/README.md
  tools/ansible/tasks/wsu/main.yaml
  tools/windows-node-installer/README.md
  tools/windows-node-installer/cmd/aws.go
  tools/windows-node-installer/cmd/azure.go
  tools/windows-node-installer/cmd/root.go
  tools/windows-node-installer/go.mod
  tools/windows-node-installer/main.go
  tools/windows-node-installer/pkg/cloudprovider/aws/ec2.go
  tools/windows-node-installer/pkg/cloudprovider/azure/vm.go
  tools/windows-node-installer/pkg/cloudprovider/factory.go
  tools/windows-node-installer/test/e2e/aws_test.go
  tools/windows-node-installer/test/e2e/azure_test.go
  tools/windows-node-installer/test/e2e/common.go
Labels: approved, lgtm, size/L

#151 [ci] Bump imported WNI to after repo rename
  internal/test/go.mod
  internal/test/go.sum
Labels: approved, lgtm, size/S

#146 [wni] Clean and bump dependencies
  tools/windows-node-installer/README.md
  tools/windows-node-installer/cmd/root.go
  tools/windows-node-installer/go.mod
  tools/windows-node-installer/go.sum
  tools/windows-node-installer/log/log.go
  tools/windows-node-installer/pkg/client/openshift.go
  tools/windows-node-installer/pkg/cloudprovider/aws/ec2.go
  tools/windows-node-installer/pkg/cloudprovider/azure/vm.go
Labels: approved, lgtm, size/L

#141 [ci] Save log files from output run
  internal/test/framework/framework.go
  internal/test/framework/windowsvm.go
  internal/test/wmcb/main_test.go
  internal/test/wsu/main_test.go
  internal/test/wsu/wsu_test.go
Labels: approved, lgtm, size/L

#142 [wsu] Check if hybrid overlay is enabled
  hack/run-wsu-ci-e2e-test.sh
  internal/test/framework/framework.go
  internal/test/go.mod
  internal/test/go.sum
  internal/test/test.go
  internal/test/wsu/wsu_test.go
  tools/ansible/tasks/wsu/main.yaml
Labels: approved, lgtm, size/L

#152 [wni] Remove secrets from log messages
  tools/windows-node-installer/pkg/cloudprovider/aws/ec2.go
Labels: approved, lgtm, size/XS

#153 [ci] Use latest WNI
  internal/test/go.mod
  internal/test/go.sum
Labels: approved, lgtm, size/XS

#150 [wni][aws] Add missing rules to Security Groups
  tools/windows-node-installer/pkg/cloudprovider/aws/ec2.go
  tools/windows-node-installer/pkg/cloudprovider/aws/ec2_test.go
Labels: approved, lgtm, size/L

#145 [ci] Re-add running WSU twice in the test suite
  internal/test/wsu/wsu_test.go
Labels: approved, lgtm, size/M

#154 Bug 1805513: Resolve parallel execution of playbook
  internal/test/wsu/main_test.go
  tools/ansible/tasks/wsu/main.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#155 [wni] Introduce WindowsVM interface
  tools/windows-node-installer/cmd/aws.go
  tools/windows-node-installer/cmd/azure.go
  tools/windows-node-installer/go.mod
  tools/windows-node-installer/go.sum
  tools/windows-node-installer/pkg/cloudprovider/aws/ec2.go
  tools/windows-node-installer/pkg/cloudprovider/azure/vm.go
  tools/windows-node-installer/pkg/cloudprovider/factory.go
  tools/windows-node-installer/pkg/types/types.go
  tools/windows-node-installer/test/e2e/aws_test.go
  tools/windows-node-installer/test/e2e/azure_test.go
  tools/windows-node-installer/test/e2e/common.go
Labels: approved, lgtm, size/L

#156 [wni][aws] Fix unit test failure for WINC-187 merge
  tools/windows-node-installer/pkg/cloudprovider/aws/ec2.go
  tools/windows-node-installer/pkg/cloudprovider/aws/ec2_test.go
Labels: approved, lgtm, size/M

#148 [wsu] Autodownload binaries based on cluster version
  internal/test/framework/windowsvm.go
  internal/test/wsu/main_test.go
  internal/test/wsu/wsu_test.go
  tools/ansible/README.md
  tools/ansible/tasks/wsu/main.yaml
Labels: approved, lgtm, size/L

#158 [ci] Add E2E test for Windows east-west networking
  internal/test/wsu/wsu_test.go
Labels: approved, lgtm, size/M
