Repository openshift/windows-machine-config-bootstrapper, pull requests merged in 2020-03, with the labels that each got.

#160 Bug 1798441: [wsu] Document API rate limiting error
  tools/ansible/README.md
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#159 [wni] Add a DestroyWindowsVM method to cloud provider interface
  tools/windows-node-installer/pkg/cloudprovider/aws/ec2.go
  tools/windows-node-installer/pkg/cloudprovider/azure/vm.go
  tools/windows-node-installer/pkg/cloudprovider/factory.go
Labels: approved, lgtm, size/M

#157 [ci] React to wni refactor
  internal/test/framework/framework.go
  internal/test/framework/windowsvm.go
  internal/test/go.mod
  internal/test/go.sum
  internal/test/wmcb/wmcb_test.go
  internal/test/wsu/wsu_test.go
Labels: approved, lgtm, size/L

#162 [wsu] [CI] Capture hybrid-overlay and kube-proxy output in artifacts_dir
  internal/test/framework/framework.go
  internal/test/framework/windowsvm.go
  internal/test/wsu/wsu_test.go
  tools/ansible/tasks/wsu/main.yaml
Labels: approved, lgtm, size/L

#166 fix windows struct nil pointer
  internal/test/framework/windowsvm.go
Labels: approved, lgtm, size/XS

#163 [wsu] Download latest 0.8.x version of CNI plugins
  internal/test/framework/framework.go
  internal/test/wmcb/main_test.go
  internal/test/wmcb/wmcb_test.go
  internal/test/wsu/wsu_test.go
  tools/ansible/tasks/wsu/main.yaml
Labels: approved, lgtm, size/L

#165 [wni] Enable SSH networking for windows node
  tools/windows-node-installer/pkg/cloudprovider/aws/ec2.go
  tools/windows-node-installer/pkg/cloudprovider/azure/vm.go
  tools/windows-node-installer/pkg/types/types.go
  tools/windows-node-installer/test/e2e/azure_test.go
  tools/windows-node-installer/test/e2e/common.go
Labels: approved, lgtm, size/M

#143 [ci] Revert OVN workaround
  hack/run-wsu-ci-e2e-test.sh
  internal/test/wsu/wsu_test.go
Labels: approved, lgtm, size/XS

#167 Bug 1809291: [wsu] Ensure kube-proxy service is not running.
  tools/ansible/tasks/wsu/main.yaml
Labels: approved, bugzilla/valid-bug, lgtm

#168 [docs][wni] Readme ENV variable fix
  tools/windows-node-installer/README.md
Labels: approved, lgtm

#169 [docs] Update Contribution Guidelines
  CONTRIBUTION.md
Labels: approved, lgtm
