Repository openshift/windows-machine-config-bootstrapper, pull requests merged in 2021-01, with the labels that each got.

#242 Dockerfile.tools: Clone WMCO repo and build submodules from there
  Dockerfile.tools
Labels: approved, lgtm

#246 WINC-480: [wmcb] Remove ansible playbooks from bootstrapper
  docs/README.md
  tools/ansible/README.md
  tools/ansible/docs/aws/aws-with-windows-server.md
  tools/ansible/docs/azure/azure-with-windows-server.md
  tools/ansible/docs/images/aws-add-tags.png
  tools/ansible/docs/images/aws-apply-role.png
  tools/ansible/docs/images/aws-attach-replace-iam-role.png
  tools/ansible/docs/images/aws-autoassign.png
  tools/ansible/docs/images/aws-change-security-groups.png
  tools/ansible/docs/images/aws-connect-get-password.png
  tools/ansible/docs/images/aws-connect-to-instance.png
  tools/ansible/docs/images/aws-connect.png
  tools/ansible/docs/images/aws-create-instance.png
  tools/ansible/docs/images/aws-edit-inbound-rules.png
  tools/ansible/docs/images/aws-enable-autoassign.png
  tools/ansible/docs/images/aws-instance-type.png
  tools/ansible/docs/images/aws-launch.png
  tools/ansible/docs/images/aws-new-key-pair.png
  tools/ansible/docs/images/aws-next-steps.png
  tools/ansible/docs/images/aws-resources.png
  tools/ansible/docs/images/aws-security-group.png
  tools/ansible/docs/images/aws-tags.png
  tools/ansible/docs/images/aws-vpc.png
  tools/ansible/docs/images/aws-windows-server.png
  tools/ansible/docs/images/azure-admin-account.png
  tools/ansible/docs/images/azure-create-instance-complete.png
  tools/ansible/docs/images/azure-create-instance.png
  tools/ansible/docs/images/azure-create-resource.png
  tools/ansible/docs/images/azure-inbound-security-rules.png
  tools/ansible/docs/images/azure-load-balancer.png
  tools/ansible/docs/images/azure-networking.png
  tools/ansible/docs/images/azure-public-ip-info.png
  tools/ansible/docs/images/azure-public-ip.png
  tools/ansible/docs/images/azure-resource-group-region.png
  tools/ansible/docs/images/azure-security-comms.png
  tools/ansible/docs/images/azure-security-groups.png
  tools/ansible/docs/images/azure-security-rdp.png
  tools/ansible/docs/images/azure-security-rules-final.png
  tools/ansible/docs/images/azure-security-winrm.png
  tools/ansible/docs/images/azure-set-load-balancer.png
  tools/ansible/docs/images/azure-tags.png
  tools/ansible/docs/images/azure-vm.png
  tools/ansible/docs/images/gen-public-ip.png
  tools/ansible/docs/ocp-4-4-with-windows-server.md
  tools/ansible/tasks/logging/README.md
  tools/ansible/tasks/logging/install_fluentd.yml
  tools/ansible/tasks/logging/install_plugins.yml
  tools/ansible/tasks/logging/main.yml
  tools/ansible/tasks/logging/test/logging_test.go
  tools/ansible/tasks/wsu/main.yaml
  tools/ansible/tasks/wsu/powershell/hns.psm1
  tools/ansible/tasks/wsu/templates/cni.j2
Labels: approved, lgtm

#255 WINC-480: [community-4.6][wmcb] Remove ansible playbooks from bootstrapper
  docs/README.md
  tools/ansible/README.md
  tools/ansible/docs/aws/aws-with-windows-server.md
  tools/ansible/docs/azure/azure-with-windows-server.md
  tools/ansible/docs/images/aws-add-tags.png
  tools/ansible/docs/images/aws-apply-role.png
  tools/ansible/docs/images/aws-attach-replace-iam-role.png
  tools/ansible/docs/images/aws-autoassign.png
  tools/ansible/docs/images/aws-change-security-groups.png
  tools/ansible/docs/images/aws-connect-get-password.png
  tools/ansible/docs/images/aws-connect-to-instance.png
  tools/ansible/docs/images/aws-connect.png
  tools/ansible/docs/images/aws-create-instance.png
  tools/ansible/docs/images/aws-edit-inbound-rules.png
  tools/ansible/docs/images/aws-enable-autoassign.png
  tools/ansible/docs/images/aws-instance-type.png
  tools/ansible/docs/images/aws-launch.png
  tools/ansible/docs/images/aws-new-key-pair.png
  tools/ansible/docs/images/aws-next-steps.png
  tools/ansible/docs/images/aws-resources.png
  tools/ansible/docs/images/aws-security-group.png
  tools/ansible/docs/images/aws-tags.png
  tools/ansible/docs/images/aws-vpc.png
  tools/ansible/docs/images/aws-windows-server.png
  tools/ansible/docs/images/azure-admin-account.png
  tools/ansible/docs/images/azure-create-instance-complete.png
  tools/ansible/docs/images/azure-create-instance.png
  tools/ansible/docs/images/azure-create-resource.png
  tools/ansible/docs/images/azure-inbound-security-rules.png
  tools/ansible/docs/images/azure-load-balancer.png
  tools/ansible/docs/images/azure-networking.png
  tools/ansible/docs/images/azure-public-ip-info.png
  tools/ansible/docs/images/azure-public-ip.png
  tools/ansible/docs/images/azure-resource-group-region.png
  tools/ansible/docs/images/azure-security-comms.png
  tools/ansible/docs/images/azure-security-groups.png
  tools/ansible/docs/images/azure-security-rdp.png
  tools/ansible/docs/images/azure-security-rules-final.png
  tools/ansible/docs/images/azure-security-winrm.png
  tools/ansible/docs/images/azure-set-load-balancer.png
  tools/ansible/docs/images/azure-tags.png
  tools/ansible/docs/images/azure-vm.png
  tools/ansible/docs/images/gen-public-ip.png
  tools/ansible/docs/ocp-4-4-with-windows-server.md
  tools/ansible/tasks/logging/README.md
  tools/ansible/tasks/logging/install_fluentd.yml
  tools/ansible/tasks/logging/install_plugins.yml
  tools/ansible/tasks/logging/main.yml
  tools/ansible/tasks/logging/test/logging_test.go
  tools/ansible/tasks/wsu/main.yaml
  tools/ansible/tasks/wsu/powershell/hns.psm1
  tools/ansible/tasks/wsu/templates/cni.j2
Labels: approved, lgtm

#253 Bug 1894649: [community-4.6] Fix Node NotReady state when updating Kubelet service.
  internal/test/wmcb/wmcb_test.go
  pkg/bootstrapper/bootstrapper.go
Labels: approved, bugzilla/invalid-bug, bugzilla/severity-high, lgtm

#248 [community-4.6] Dockerfile.tools: Clone WMCO repo and build submodules from there
  Dockerfile.tools
Labels: approved, lgtm

#256 Bug 1903330: WMCO successfully reconciles with incorrect configure-cni command
  cmd/bootstrapper/main.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#241 Bug 1904605: [release-4.6] Update Kubelet service in-place instead of recreating
  go.mod
  internal/test/wmcb/wmcb_test.go
  pkg/bootstrapper/bootstrapper.go
  pkg/bootstrapper/kubelet.go
  test/e2e/bootstrapper_test.go
  vendor/k8s.io/apimachinery/pkg/util/wait/doc.go
  vendor/k8s.io/apimachinery/pkg/util/wait/wait.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#251 [ci] Define build_root_image within WMCB repo
  .ci-operator.yaml
Labels: approved, lgtm

#247 [release-4.6] Dockerfile.tools: Clone WMCO repo and build submodules from there
  Dockerfile.tools
Labels: approved, lgtm

#257 Add sebsoto as an approver
  OWNERS
Labels: approved, lgtm

#250 WINC-480: [release-4.6][wmcb] Remove ansible playbooks from bootstrapper
  docs/README.md
  tools/ansible/README.md
  tools/ansible/docs/aws/aws-with-windows-server.md
  tools/ansible/docs/azure/azure-with-windows-server.md
  tools/ansible/docs/images/aws-add-tags.png
  tools/ansible/docs/images/aws-apply-role.png
  tools/ansible/docs/images/aws-attach-replace-iam-role.png
  tools/ansible/docs/images/aws-autoassign.png
  tools/ansible/docs/images/aws-change-security-groups.png
  tools/ansible/docs/images/aws-connect-get-password.png
  tools/ansible/docs/images/aws-connect-to-instance.png
  tools/ansible/docs/images/aws-connect.png
  tools/ansible/docs/images/aws-create-instance.png
  tools/ansible/docs/images/aws-edit-inbound-rules.png
  tools/ansible/docs/images/aws-enable-autoassign.png
  tools/ansible/docs/images/aws-instance-type.png
  tools/ansible/docs/images/aws-launch.png
  tools/ansible/docs/images/aws-new-key-pair.png
  tools/ansible/docs/images/aws-next-steps.png
  tools/ansible/docs/images/aws-resources.png
  tools/ansible/docs/images/aws-security-group.png
  tools/ansible/docs/images/aws-tags.png
  tools/ansible/docs/images/aws-vpc.png
  tools/ansible/docs/images/aws-windows-server.png
  tools/ansible/docs/images/azure-admin-account.png
  tools/ansible/docs/images/azure-create-instance-complete.png
  tools/ansible/docs/images/azure-create-instance.png
  tools/ansible/docs/images/azure-create-resource.png
  tools/ansible/docs/images/azure-inbound-security-rules.png
  tools/ansible/docs/images/azure-load-balancer.png
  tools/ansible/docs/images/azure-networking.png
  tools/ansible/docs/images/azure-public-ip-info.png
  tools/ansible/docs/images/azure-public-ip.png
  tools/ansible/docs/images/azure-resource-group-region.png
  tools/ansible/docs/images/azure-security-comms.png
  tools/ansible/docs/images/azure-security-groups.png
  tools/ansible/docs/images/azure-security-rdp.png
  tools/ansible/docs/images/azure-security-rules-final.png
  tools/ansible/docs/images/azure-security-winrm.png
  tools/ansible/docs/images/azure-set-load-balancer.png
  tools/ansible/docs/images/azure-tags.png
  tools/ansible/docs/images/azure-vm.png
  tools/ansible/docs/images/gen-public-ip.png
  tools/ansible/docs/ocp-4-4-with-windows-server.md
  tools/ansible/tasks/logging/README.md
  tools/ansible/tasks/logging/install_fluentd.yml
  tools/ansible/tasks/logging/install_plugins.yml
  tools/ansible/tasks/logging/main.yml
  tools/ansible/tasks/logging/test/logging_test.go
  tools/ansible/tasks/wsu/main.yaml
  tools/ansible/tasks/wsu/powershell/hns.psm1
  tools/ansible/tasks/wsu/templates/cni.j2
Labels: approved, lgtm
